// <auto-generated />
using System.Collections.Generic;
using MetricsTogglesDebt.Data;
using MetricsTogglesDebt.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetricsTogglesDebt.Data.Migrations
{
    [DbContext(typeof(MetricsTogglesDebtDbContext))]
    [Migration("20230809124807_edit-table_commit")]
    partial class edittable_commit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MetricsTogglesDebt.Data.Entities.ClassesAndMethods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Found")
                        .HasColumnType("boolean");

                    b.Property<List<string>>("FoundPaths")
                        .HasColumnType("jsonb");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClassesAndMethods");
                });

            modelBuilder.Entity("MetricsTogglesDebt.Data.Entities.Commit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Author>("Author")
                        .HasColumnType("jsonb")
                        .HasAnnotation("Relational:JsonPropertyName", "author");

                    b.Property<Committer>("Committer")
                        .HasColumnType("jsonb")
                        .HasAnnotation("Relational:JsonPropertyName", "committer");

                    b.Property<GPG>("GPG")
                        .HasColumnType("jsonb")
                        .HasAnnotation("Relational:JsonPropertyName", "GPG");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "message");

                    b.Property<List<string>>("Parents")
                        .HasColumnType("jsonb")
                        .HasAnnotation("Relational:JsonPropertyName", "parents");

                    b.Property<List<string>>("Refs")
                        .HasColumnType("jsonb")
                        .HasAnnotation("Relational:JsonPropertyName", "refs");

                    b.Property<string>("Sha1")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "sha1");

                    b.Property<List<string>>("Tags")
                        .HasColumnType("jsonb")
                        .HasAnnotation("Relational:JsonPropertyName", "tags");

                    b.Property<string>("Tree")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "tree");

                    b.HasKey("Id");

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("MetricsTogglesDebt.Data.Entities.LinesOfCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Blank")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("File")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("Lines")
                        .HasColumnType("text");

                    b.Property<List<string>>("SpecialCharacters")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("LinesOfCode");
                });
#pragma warning restore 612, 618
        }
    }
}
