// <auto-generated />
using System.Collections.Generic;
using MetricsTogglesDebt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetricsTogglesDebt.Data.Migrations
{
    [DbContext(typeof(MetricsTogglesDebtDbContext))]
    partial class MetricsTogglesDebtDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MetricsTogglesDebt.Data.Entities.ClassesAndMethods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Found")
                        .HasColumnType("boolean");

                    b.Property<List<string>>("FoundPaths")
                        .HasColumnType("jsonb");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClassesAndMethods");
                });

            modelBuilder.Entity("MetricsTogglesDebt.Data.Entities.LinesOfCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Blank")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("File")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("Lines")
                        .HasColumnType("text");

                    b.Property<List<string>>("SpecialCharacters")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("LinesOfCode");
                });
#pragma warning restore 612, 618
        }
    }
}
